# Author
author:
 name: 'JFRN'
 url: http://jfrn.github.io
 email: jfrn.josefer@gmail.com
 twitter: DarkJFRN
 github: JFRN
 googleplus: Jos%C3%A9FernandoRadaNarv%C3%A1ezJFRN

# Custom vars
github:
  repo: https://github.com/jfrn/jfrn.github.io

# Website
description: 'A website about myself and things I publish on the internet.'
url: http://jfrn.github.io
title: JFRN
name: JFRN
tagline: '' # what will appear along the site name
timezone: America/Mexico_City
encoding: utf-8
url: jfrn.github.io
permalink: pretty
baseurl: ''

# Comments
disqus: jfrn-io
# Pagination
paginate: 7

# Directives
markdown: kramdown
kramdown:
 # Use GitHub flavored markdown, including triple backtick fenced code blocks
 input: GFM
 # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
 syntax_highlighter: rouge
 syntax_highlighter_opts:
  css_class: 'highlight' # Use existing pygments syntax highlighting css
# Gems

gems:
  - jekyll-paginate #Old dependency of the theme
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed
  - jekyll-gist # Create an Atom feed using the official Jekyll feed gem

# Exclude

exclude:
 - Gemfile
 - Gemfile.lock
 - LICENSE
 - README.md
 - CNAME
 - old-site
