# Dependencies

markdown: kramdown
kramdown:
  input: GFM
gems:
  - jekyll-paginate

# Setup

title: José Rada
name: José Rada
tagline: 'Just learning'
description: 'A website about myself and things I publish on the internet.'
url: http://jfrn.github.io
author:
  name: 'José Rada'
  url: http://jfrn.github.io
timezone: America/Mexico_City
encoding: utf-8

# Pagination

paginate: 7
paginate_path: "/posts/page:num/"

# Custom vars

github:
  repo: https://github.com/jfrn/jfrn.github.io

# Directives

exclude:
  - old-site/
